# Generated by Django 5.1.6 on 2025-02-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_alter_historicaltransaction_timestamp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltransaction",
            name="timestamp",
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
